### ISSUE TITLE
Entering wrong password throws exception

### ISSUE THREAD

**Issue by ulken** [Evidlo/passhole#39]
Whenever I mistype the password, I end up with:

```sh
❯ ph ls
Enter database password (<db>): 
Traceback (most recent call last):
  File "/usr/local/bin/ph", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/passhole/passhole.py", line 1032, in main
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/passhole/passhole.py", line 643, in list_entries
    databases = open_database(all=True, **vars(args))
  File "/usr/local/lib/python3.8/site-packages/passhole/passhole.py", line 410, in open_database
    kp = prompt_open(
  File "/usr/local/lib/python3.8/site-packages/passhole/passhole.py", line 370, in prompt_open
    return PyKeePass(database, password=password, keyfile=keyfile, timeout=cache_timeout)
  File "/usr/local/lib/python3.8/site-packages/pykeepass_cache/pykeepass_cache.py", line 176, in PyKeePass
    return _fork_and_run(func, timeout=timeout, socket_path=socket_path)
  File "/usr/local/lib/python3.8/site-packages/pykeepass_cache/pykeepass_cache.py", line 95, in _fork_and_run
    return func(conn)
  File "/usr/local/lib/python3.8/site-packages/pykeepass_cache/pykeepass_cache.py", line 175, in <lambda>
    func = lambda conn: conn.root.PyKeePass(filename, password, keyfile, transformed_key)
  File "/usr/local/lib/python3.8/site-packages/rpyc/core/netref.py", line 253, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 469, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/local/lib/python3.8/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
rpyc.core.vinegar/pykeepass.exceptions.CredentialsError: 

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 95, in read
    self.kdbx = KDBX.parse_file(
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 309, in parse_file
    return self.parse_stream(f, **contextkw)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 1982, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 2440, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 3628, in _parse
    return sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 1982, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 2440, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 698, in _parse
    return self._decode(obj, context, path)
  File "/usr/local/lib/python3.8/site-packages/pykeepass/kdbx_parsing/common.py", line 76, in _decode
    return subcon_out.parse(data, **con)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 1982, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 2440, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.8/site-packages/construct/core.py", line 5078, in _parse
    raise ChecksumError(
construct.core.ChecksumError: Error in path (parsing) -> cred_check
wrong checksum, read b'2172fea47bb6b73de509ea438046b4f5db89e19312f21390ac905acc2bc5c0c6', computed b'de99deeba4727843158d8578652b769c61b5fa9fc48460adf093ab0387f59a9a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python3.8/site-packages/rpyc/core/protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/usr/local/lib/python3.8/site-packages/pykeepass_cache/pykeepass_cache.py", line 43, in exposed_PyKeePass
    kp = PyKeePass(filename, password, keyfile)
  File "/usr/local/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 65, in __init__
    self.read(
  File "/usr/local/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 106, in read
    raise CredentialsError
pykeepass.exceptions.CredentialsError
```

I get that it's a type of error, but I would prefer to be presented with something more user-friendly.

I'm on macOS if that makes any difference.

**Comment by Evidlo** [comment]
This should be fixed with the latest commit.  Let me know what you think.

**Comment by ulken** [comment]
Alright! Will do. Thanks!

**Comment by ulken** [comment]
> This should be fixed with the latest commit. Let me know what you think.

I'm afraid not. Running version `1.9.4` and it still throws the (seemingly) same error.

**Comment by ulken** [comment]
Let me know if I can provide any more debug information.

**Comment by Evidlo** [comment]
Sorry, I forgot to push my commit.  Try now.

**Comment by ulken** [comment]
Confirmed! Upgrading to the latest commit works beautifully. Thank you!
